In [1]:
from Code import *
from Code.environment import *
from Code.data import *

from Code.environment.Environment import Environment

In [2]:
cust_json = "customer_classes.json"
today_customer = 100
var_cust = 10
p_lambda = 0.5
graph_json = "business_full_graph.json"

environment = Environment(cust_json,today_customer,var_cust,p_lambda, graph_json)

In [3]:
from Code.GreedyLearner import GreedyLearner
from Code.environment.Customer import Customer

In [6]:
import numpy as np

In [11]:
n_arms = 4
n_products = 5 

feature1 = 0
feature2 = 0

customer = Customer(feature1, feature2)

arms = np.full((n_products,n_arms),np.random.uniform(0,10))
print(arms)

gr_learner = GreedyLearner(n_arms, n_products, customer, graph_json, arms)

[[6.47169757 6.47169757 6.47169757 6.47169757]
 [6.47169757 6.47169757 6.47169757 6.47169757]
 [6.47169757 6.47169757 6.47169757 6.47169757]
 [6.47169757 6.47169757 6.47169757 6.47169757]
 [6.47169757 6.47169757 6.47169757 6.47169757]]


TypeError: __init__() takes 5 positional arguments but 6 were given