In [1]:
import copy
import numpy as np
import matplotlib.pyplot as plt


import Code.utils as utils
import Code.environment.settings as settings
from Code.environment.EnvironmentNonStationary import EnvironmentNonStationary
from Code.GreedyLearner import GreedyLearner
from Code.environment.Customer import Customer
from Code.UCBLearner import UCBLearner
from Code.UCBLearnerActive import UCBLearnerActive, UCBLearnerActive2
from Code.UCBLearnerSlidingWindow import UCBLearnerSlidingWindow

%matplotlib inline

In [2]:
cust_json = "customer3_n_s.json"
today_customer = 300
var_cust = 10
p_lambda = 1.0
graph_json = "business_full_graph.json"
abrupt_change_interval = 100

arms = settings.prices
environment = EnvironmentNonStationary(cust_json,today_customer,var_cust,p_lambda, graph_json, arms, abrupt_change_interval)
clairvoyant_arms, clairvoyant_reward, exp_c, s= environment.estimate_clairvoyant()
print("\n", clairvoyant_arms, clairvoyant_reward, exp_c)

loading: [                              ] 0.0%
loading: [=                             ] 1.0%
loading: [=                             ] 2.0%
loading: [=                             ] 2.9%
loading: [==                            ] 3.9%
loading: [==                            ] 4.9%
loading: [==                            ] 5.9%
loading: [===                           ] 6.8%
loading: [===                           ] 7.8%
loading: [===                           ] 8.8%
loading: [===                           ] 9.8%
loading: [====                          ] 10.7%
loading: [====                          ] 11.7%
loading: [====                          ] 12.7%
loading: [=====                         ] 13.7%
loading: [=====                         ] 14.6%
loading: [=====                         ] 15.6%
loading: [=====                         ] 16.6%
loading: [======                        ] 17.6%
loading: [======                        ] 18.6%
loading: [======                        ] 19.5%
loa

loading: [======================        ] 72.3%
loading: [======================        ] 73.2%
loading: [=======================       ] 74.2%
loading: [=======================       ] 75.2%
loading: [=======================       ] 76.2%
loading: [========================      ] 77.1%
loading: [========================      ] 78.1%
loading: [========================      ] 79.1%
loading: [=========================     ] 80.1%
loading: [=========================     ] 81.1%
loading: [=========================     ] 82.0%
loading: [=========================     ] 83.0%
loading: [==========================    ] 84.0%
loading: [==========================    ] 85.0%
loading: [==========================    ] 85.9%
loading: [===========================   ] 86.9%
loading: [===========================   ] 87.9%
loading: [===========================   ] 88.9%
loading: [===========================   ] 89.8%
loading: [============================  ] 90.8%
loading: [============================  

In [3]:
n_arms = 4
n_products = 5 

feature1 = 0
feature2 = 0

customer = Customer(feature1, feature2)

TIME_HORIZON = 300
NUM_ITERATION = 5

In [4]:
customers = copy.deepcopy(environment.customers)
for customer in customers:
    customer.set_probability_buy(np.ones_like(customer.get_buy_distribution())/2)

## UCB with abrupt change detection 1

in this case when an abrupt change is detected for a single arm, all the data are dropped

In [5]:
rewards_iterations1 = []
for i in range(NUM_ITERATION):
    ucb6_learner = UCBLearnerActive(n_arms, n_products, customers, graph_json, arms, environment.customers_distribution)
    print('Iteration #', i+1)
    for t in range(TIME_HORIZON):
        if t % 10 == 0:
            utils.progress_bar(t, TIME_HORIZON)
        super_arm = ucb6_learner.select_superarm()
        print(super_arm)
        report = environment.round(super_arm)
        ucb6_learner.update(super_arm.copy(), report)
    rewards = ucb6_learner.history_rewards
    rewards_iterations1.append(np.array(rewards))
    environment.new_iteration()
print(ucb6_learner.get_conv_rate_history())
rewards_iterations1 = np.array(rewards_iterations1)
rewards_iterations1.shape

Iteration # 1
loading: [                              ] 0.0%
[3, 3, 3, 3, 3]
t:  0
phase 0
set customer
conv_rate: [[0.   0.04 0.8  0.04]
 [0.   0.49 0.26 0.  ]
 [0.03 0.6  0.03 0.  ]
 [0.04 0.8  0.04 0.  ]
 [0.01 0.36 0.36 0.01]]
conv_rate: [[0.   0.   0.02 0.5 ]
 [0.   0.   0.   0.7 ]
 [0.   0.04 0.8  0.03]
 [0.5  0.02 0.   0.  ]
 [0.5  0.   0.   0.  ]]
conv_rate: [[0.02 0.5  0.02 0.  ]
 [0.16 0.16 0.   0.  ]
 [0.   0.   0.02 0.5 ]
 [0.18 0.04 0.   0.  ]
 [0.   0.17 0.7  0.17]]
conv_rate: [[0.02 0.5  0.02 0.  ]
 [0.16 0.16 0.   0.  ]
 [0.   0.   0.02 0.5 ]
 [0.18 0.04 0.   0.  ]
 [0.   0.17 0.7  0.17]]
[2, 2, 2, 2, 2]
t:  1
phase 0
[1, 1, 1, 1, 1]
t:  2
phase 0
[0, 0, 0, 1, 0]
t:  3
phase 0
[2, 3, 1, 0, 2]
t:  4
phase 0
[2, 1, 2, 1, 2]
t:  5
phase 0
[2, 1, 1, 0, 1]
t:  6
phase 0
[2, 3, 1, 1, 2]
t:  7
phase 0
[2, 1, 2, 1, 3]
t:  8
phase 0
[2, 2, 1, 1, 0]
t:  9
phase 0
loading: [=                             ] 3.3%
[3, 0, 1, 3, 2]
t:  10
phase 0
[2, 1, 3, 1, 2]
t:  11
phase 0
[2, 1, 1,

[2, 2, 1, 1, 2]
t:  197
phase 1
[2, 1, 1, 1, 2]
t:  198
phase 1
[2, 2, 2, 1, 2]
t:  199
phase 1
loading: [====================          ] 66.7%
[2, 2, 1, 1, 2]
t:  200
phase 2
set customer
conv_rate: [[0.   0.01 0.53 0.08]
 [0.01 0.5  0.02 0.  ]
 [0.   0.   0.1  0.62]
 [0.04 0.8  0.04 0.  ]
 [0.   0.07 0.5  0.07]]
conv_rate: [[0.   0.   0.03 0.6 ]
 [0.   0.   0.03 0.36]
 [0.   0.24 0.13 0.  ]
 [0.24 0.05 0.   0.  ]
 [0.49 0.16 0.   0.  ]]
conv_rate: [[0.   0.09 0.62 0.01]
 [0.   0.43 0.23 0.  ]
 [0.   0.01 0.44 0.07]
 [0.44 0.07 0.   0.  ]
 [0.   0.01 0.08 0.  ]]
conv_rate: [[0.   0.09 0.62 0.01]
 [0.   0.43 0.23 0.  ]
 [0.   0.01 0.44 0.07]
 [0.44 0.07 0.   0.  ]
 [0.   0.01 0.08 0.  ]]
[2, 1, 3, 1, 2]
t:  201
phase 2
[2, 1, 3, 1, 2]
t:  202
phase 2
[2, 1, 3, 1, 2]
t:  203
phase 2
[2, 1, 3, 1, 2]
t:  204
phase 2
[2, 1, 3, 1, 2]
t:  205
phase 2
[2, 1, 3, 1, 2]
t:  206
phase 2
[2, 1, 3, 1, 2]
t:  207
phase 2
[2, 1, 3, 1, 2]
t:  208
phase 2
[2, 1, 3, 1, 2]
t:  209
phase 2
loading: [=====

[2, 1, 1, 1, 2]
t:  94
phase 0
[2, 1, 1, 1, 2]
t:  95
phase 0
[2, 1, 1, 1, 2]
t:  96
phase 0
[2, 1, 1, 1, 2]
t:  97
phase 0
[2, 1, 1, 1, 2]
t:  98
phase 0
[2, 1, 1, 1, 2]
t:  99
phase 0
loading: [==========                    ] 33.3%
[2, 1, 1, 1, 2]
t:  100
phase 1
set customer
conv_rate: [[0.   0.   0.24 0.13]
 [0.18 0.   0.   0.  ]
 [0.   0.   0.16 0.3 ]
 [0.4  0.02 0.   0.  ]
 [0.   0.08 0.28 0.02]]
conv_rate: [[0.   0.02 0.4  0.02]
 [0.   0.01 0.44 0.01]
 [0.01 0.2  0.01 0.  ]
 [0.3  0.5  0.3  0.07]
 [0.   0.02 0.35 0.35]]
conv_rate: [[0.   0.3  0.16 0.  ]
 [0.   0.24 0.13 0.  ]
 [0.   0.13 0.24 0.  ]
 [0.18 0.1  0.   0.  ]
 [0.   0.   0.44 0.  ]]
conv_rate: [[0.   0.3  0.16 0.  ]
 [0.   0.24 0.13 0.  ]
 [0.   0.13 0.24 0.  ]
 [0.18 0.1  0.   0.  ]
 [0.   0.   0.44 0.  ]]
[2, 1, 2, 1, 2]
t:  101
phase 1
[2, 1, 1, 1, 2]
t:  102
phase 1
[2, 1, 1, 1, 2]
t:  103
phase 1
[2, 3, 3, 1, 2]
t:  104
phase 1
[2, 1, 1, 1, 2]
t:  105
phase 1
abrupt change
[3, 3, 3, 3, 3]
t:  106
phase 1
[1, 2, 

[2, 1, 3, 1, 2]
t:  289
phase 2
loading: [============================= ] 96.7%
[2, 1, 3, 1, 2]
t:  290
phase 2
[2, 1, 3, 1, 2]
t:  291
phase 2
[2, 1, 3, 1, 2]
t:  292
phase 2
[2, 1, 3, 1, 2]
t:  293
phase 2
[2, 1, 3, 1, 2]
t:  294
phase 2
[2, 1, 3, 1, 2]
t:  295
phase 2
[2, 1, 3, 1, 2]
t:  296
phase 2
[2, 1, 3, 1, 2]
t:  297
phase 2
[2, 1, 3, 1, 2]
t:  298
phase 2
[2, 1, 3, 1, 2]
t:  299
phase 2
Iteration # 3
loading: [                              ] 0.0%
[3, 3, 3, 3, 3]
t:  0
phase 0
set customer
conv_rate: [[0.   0.04 0.8  0.04]
 [0.   0.49 0.26 0.  ]
 [0.03 0.6  0.03 0.  ]
 [0.04 0.8  0.04 0.  ]
 [0.01 0.36 0.36 0.01]]
conv_rate: [[0.   0.   0.02 0.5 ]
 [0.   0.   0.   0.7 ]
 [0.   0.04 0.8  0.03]
 [0.5  0.02 0.   0.  ]
 [0.5  0.   0.   0.  ]]
conv_rate: [[0.02 0.5  0.02 0.  ]
 [0.16 0.16 0.   0.  ]
 [0.   0.   0.02 0.5 ]
 [0.18 0.04 0.   0.  ]
 [0.   0.17 0.7  0.17]]
conv_rate: [[0.02 0.5  0.02 0.  ]
 [0.16 0.16 0.   0.  ]
 [0.   0.   0.02 0.5 ]
 [0.18 0.04 0.   0.  ]
 [0.   0.17 

[2, 1, 2, 1, 2]
t:  186
phase 1
[2, 2, 1, 1, 2]
t:  187
phase 1
[2, 2, 1, 1, 2]
t:  188
phase 1
[2, 2, 3, 1, 2]
t:  189
phase 1
loading: [===================           ] 63.3%
[2, 2, 1, 1, 2]
t:  190
phase 1
[2, 1, 1, 0, 2]
t:  191
phase 1
[2, 2, 1, 1, 2]
t:  192
phase 1
[2, 2, 1, 1, 2]
t:  193
phase 1
[2, 2, 2, 1, 2]
t:  194
phase 1
[2, 1, 1, 1, 2]
t:  195
phase 1
[2, 2, 1, 0, 2]
t:  196
phase 1
[2, 2, 3, 0, 2]
t:  197
phase 1
[2, 1, 1, 1, 2]
t:  198
phase 1
[2, 2, 1, 1, 2]
t:  199
phase 1
loading: [====================          ] 66.7%
[2, 2, 1, 2, 2]
t:  200
phase 2
set customer
conv_rate: [[0.   0.01 0.53 0.08]
 [0.01 0.5  0.02 0.  ]
 [0.   0.   0.1  0.62]
 [0.04 0.8  0.04 0.  ]
 [0.   0.07 0.5  0.07]]
conv_rate: [[0.   0.   0.03 0.6 ]
 [0.   0.   0.03 0.36]
 [0.   0.24 0.13 0.  ]
 [0.24 0.05 0.   0.  ]
 [0.49 0.16 0.   0.  ]]
conv_rate: [[0.   0.09 0.62 0.01]
 [0.   0.43 0.23 0.  ]
 [0.   0.01 0.44 0.07]
 [0.44 0.07 0.   0.  ]
 [0.   0.01 0.08 0.  ]]
conv_rate: [[0.   0.09 0.62 0.

[2, 3, 1, 1, 2]
t:  82
phase 0
[2, 1, 2, 1, 2]
t:  83
phase 0
[2, 1, 1, 1, 2]
t:  84
phase 0
[2, 1, 1, 1, 2]
t:  85
phase 0
[2, 1, 1, 1, 2]
t:  86
phase 0
[2, 1, 1, 1, 2]
t:  87
phase 0
[2, 1, 1, 1, 2]
t:  88
phase 0
[2, 1, 1, 1, 2]
t:  89
phase 0
loading: [=========                     ] 30.0%
[2, 1, 1, 1, 2]
t:  90
phase 0
[2, 1, 1, 1, 2]
t:  91
phase 0
[2, 1, 1, 1, 2]
t:  92
phase 0
[2, 1, 1, 1, 2]
t:  93
phase 0
[2, 1, 1, 1, 2]
t:  94
phase 0
[2, 1, 1, 1, 2]
t:  95
phase 0
[2, 1, 1, 1, 2]
t:  96
phase 0
[2, 1, 1, 0, 2]
t:  97
phase 0
[2, 1, 1, 1, 2]
t:  98
phase 0
[2, 1, 1, 1, 2]
t:  99
phase 0
loading: [==========                    ] 33.3%
[2, 1, 1, 1, 2]
t:  100
phase 1
set customer
conv_rate: [[0.   0.   0.24 0.13]
 [0.18 0.   0.   0.  ]
 [0.   0.   0.16 0.3 ]
 [0.4  0.02 0.   0.  ]
 [0.   0.08 0.28 0.02]]
conv_rate: [[0.   0.02 0.4  0.02]
 [0.   0.01 0.44 0.01]
 [0.01 0.2  0.01 0.  ]
 [0.3  0.5  0.3  0.07]
 [0.   0.02 0.35 0.35]]
conv_rate: [[0.   0.3  0.16 0.  ]
 [0.   0.24 0

[2, 1, 3, 1, 2]
t:  278
phase 2
[2, 1, 3, 1, 2]
t:  279
phase 2
loading: [============================  ] 93.3%
[2, 1, 3, 1, 2]
t:  280
phase 2
[2, 1, 3, 1, 2]
t:  281
phase 2
[2, 1, 3, 1, 2]
t:  282
phase 2
[2, 1, 3, 1, 2]
t:  283
phase 2
[2, 1, 3, 1, 2]
t:  284
phase 2
[2, 1, 3, 1, 2]
t:  285
phase 2
[2, 1, 3, 1, 2]
t:  286
phase 2
[2, 1, 3, 1, 2]
t:  287
phase 2
[2, 1, 3, 1, 2]
t:  288
phase 2
[2, 1, 3, 1, 2]
t:  289
phase 2
loading: [============================= ] 96.7%
[2, 1, 3, 1, 2]
t:  290
phase 2
[2, 1, 3, 1, 2]
t:  291
phase 2
[2, 1, 3, 1, 2]
t:  292
phase 2
[2, 1, 3, 1, 2]
t:  293
phase 2
[2, 1, 3, 1, 2]
t:  294
phase 2
[2, 1, 3, 1, 2]
t:  295
phase 2
[2, 1, 3, 1, 2]
t:  296
phase 2
[2, 1, 3, 1, 2]
t:  297
phase 2
[2, 1, 3, 1, 2]
t:  298
phase 2
[2, 1, 3, 1, 2]
t:  299
phase 2
Iteration # 5
loading: [                              ] 0.0%
[3, 3, 3, 3, 3]
t:  0
phase 0
set customer
conv_rate: [[0.   0.04 0.8  0.04]
 [0.   0.49 0.26 0.  ]
 [0.03 0.6  0.03 0.  ]
 [0.04 0.8  0.04

[2, 0, 3, 0, 2]
t:  175
phase 1
[2, 2, 2, 0, 2]
t:  176
phase 1
[2, 2, 1, 0, 2]
t:  177
phase 1
[2, 3, 3, 0, 2]
t:  178
phase 1
[2, 2, 3, 2, 2]
t:  179
phase 1
loading: [==================            ] 60.0%
[2, 2, 2, 1, 2]
t:  180
phase 1
[3, 2, 3, 1, 2]
t:  181
phase 1
[2, 2, 3, 0, 2]
t:  182
phase 1
[2, 2, 2, 0, 2]
t:  183
phase 1
[2, 2, 3, 0, 0]
t:  184
phase 1
[2, 2, 3, 0, 2]
t:  185
phase 1
[2, 2, 1, 0, 2]
t:  186
phase 1
[2, 2, 3, 0, 2]
t:  187
phase 1
[2, 2, 3, 0, 2]
t:  188
phase 1
[2, 2, 3, 0, 2]
t:  189
phase 1
loading: [===================           ] 63.3%
[2, 2, 2, 0, 2]
t:  190
phase 1
[2, 1, 3, 0, 2]
t:  191
phase 1
[2, 2, 2, 0, 2]
t:  192
phase 1
[2, 2, 3, 3, 2]
t:  193
phase 1
[2, 0, 2, 1, 2]
t:  194
phase 1
[2, 2, 1, 0, 2]
t:  195
phase 1
[2, 2, 3, 0, 2]
t:  196
phase 1
[2, 2, 2, 0, 2]
t:  197
phase 1
[2, 2, 2, 0, 2]
t:  198
phase 1
[2, 2, 1, 2, 2]
t:  199
phase 1
loading: [====================          ] 66.7%
[2, 2, 2, 0, 2]
t:  200
phase 2
set customer
conv_rate: 

(5, 300)

In [6]:
plt.figure(figsize=(12, 7))
mean1 = np.mean(rewards_iterations, axis=0)
stdev1 = np.std(rewards_iterations, axis=0)


plt.plot(range(len(mean1)), mean1)
plt.fill_between(range(len(mean1)), (mean1-stdev1), (mean1+stdev1), color='b', alpha=.1)
rews_c = [clairvoyant_reward[0]] * abrupt_change_interval + [clairvoyant_reward[1]] * abrupt_change_interval + [clairvoyant_reward[2]] * abrupt_change_interval
plt.plot([_ for _ in range(len(rews_c))], rews_c, color="green", label="clairvoyant")
plt.axvline(x=100, color="red", label="first abrupt change")
plt.axvline(x=200, color="orange", label="second abrupt change")
plt.legend()
plt.show()

NameError: name 'rewards_iterations' is not defined

<Figure size 864x504 with 0 Axes>

In [ ]:
plt.figure(figsize=(8,5))
regret1 = rews_c - rewards_iterations 
mean_regret1 = np.mean(regret1, axis=0)
std_regret1 = np.std(regret1, axis=0)

plt.plot(range(len(mean_regret1)), mean_regret1)
plt.fill_between(range(len(mean_regret1)), (mean_regret1-std_regret1), (mean_regret1+std_regret1), color='b', alpha=.1)
plt.axvline(x=100, color="red", label="first abrupt change")
plt.axvline(x=200, color="orange", label="second abrupt change")
plt.legend()
plt.show()

In [ ]:
plt.figure(figsize=(8,5))
regret1 = rews_c - rewards_iterations1 
cumulative_regret1 = np.cumsum(regret1, axis=1)
cum_reg_mean1 = np.mean(cumulative_regret1, axis=0)
cum_reg_std1 = np.std(cumulative_regret1, axis=0)

plt.plot(range(len(cum_reg_mean1)), cum_reg_mean1)
plt.fill_between(range(len(cum_reg_mean1)), (cum_reg_mean1-cum_reg_std1), (cum_reg_mean1+cum_reg_std1), color='b', alpha=.1)
plt.axvline(x=100, color="red", label="first abrupt change")
plt.axvline(x=200, color="orange", label="second abrupt change")
plt.legend()
plt.show()

## UCB with abrupt change detection 2

in this case when an abrupt change is detected for a single arm, only the data reletad to that arm are dropped

In [ ]:
customers = copy.deepcopy(environment.customers)
for customer in customers:
    customer.set_probability_buy(np.ones_like(customer.get_buy_distribution())/2)

In [ ]:
rewards_iterations2 = []
for i in range(NUM_ITERATION):
    ucb6_learner = UCBLearnerActive2(n_arms, n_products, customers, graph_json, arms, environment.customers_distribution)
    print('Iteration #', i+1)
    for t in range(TIME_HORIZON):
        if t % 10 == 0:
            utils.progress_bar(t, TIME_HORIZON)
        super_arm = ucb6_learner.select_superarm()
        print(super_arm)
        report = environment.round(super_arm)
        ucb6_learner.update(super_arm.copy(), report)
    rewards = ucb6_learner.history_rewards
    rewards_iterations2.append(np.array(rewards))
    environment.new_iteration()
rewards_iterations2 = np.array(rewards_iterations2)
rewards_iterations2.shape

In [ ]:
plt.figure(figsize=(12, 7))
mean2 = np.mean2(rewards_iterations2, axis=0)
stdev2 = np.std2(rewards_iterations2, axis=0)


plt.plot(range(len(mean2)), mean2)
plt.fill_between(range(len(mean2)), (mean2-stdev2), (mean2+stdev2), color='b', alpha=.1)
rews_c = [clairvoyant_reward[0]] * abrupt_change_interval + [clairvoyant_reward[1]] * abrupt_change_interval + [clairvoyant_reward[2]] * abrupt_change_interval
plt.plot([_ for _ in range(len(rews_c))], rews_c, color="green", label="clairvoyant")
plt.axvline(x=100, color="red", label="first abrupt change")
plt.axvline(x=200, color="orange", label="second abrupt change")
plt.legend()
plt.show()

In [ ]:
plt.figure(figsize=(8,5))
regret2 = rews_c - rewards_iterations2
mean_regret2 = np.mean(regret2, axis=0)
std_regret2 = np.std(regret2, axis=0)

plt.plot(range(len(mean_regret2)), mean_regret2)
plt.fill_between(range(len(mean_regret2)), (mean_regret2-std_regret2), (mean_regret2+std_regret2), color='b', alpha=.1)
plt.axvline(x=100, color="red", label="first abrupt change")
plt.axvline(x=200, color="orange", label="second abrupt change")
plt.legend()
plt.show()

In [ ]:
plt.figure(figsize=(8,5))
regret2 = rews_c - rewards_iterations2
cumulative_regret2 = np.cumsum(regret2, axis=1)
cum_reg_mean2 = np.mean(cumulative_regret2, axis=0)
cum_reg_std2 = np.std(cumulative_regret2, axis=0)

plt.plot(range(len(cum_reg_mean2)), cum_reg_mean2)
plt.fill_between(range(len(cum_reg_mean2)), (cum_reg_mean2-cum_reg_std2), (cum_reg_mean2+cum_reg_std2), color='b', alpha=.1)
plt.axvline(x=100, color="red", label="first abrupt change")
plt.axvline(x=200, color="orange", label="second abrupt change")
plt.legend()
plt.show()

## Comparison between UCBLearnerActive1 and UCBLearnerActive2

cumulative reward comparison

In [ ]:
plt.figure(figsize=(12, 7))
plt.plot(range(len(mean2)), mean2, color="blue", label="UCBLearnerActive2")
plt.fill_between(range(len(mean2)), (mean2-stdev2), (mean2+stdev2), color='b', alpha=.1)

plt.plot(range(len(mean1)), mean1, color="green", label="UCBLearnerActive1")
plt.fill_between(range(len(mean1)), (mean1-stdev1), (mean1+stdev1), color="green", alpha=.1)

rews_c = [clairvoyant_reward[0]] * abrupt_change_interval + [clairvoyant_reward[1]] * abrupt_change_interval + [clairvoyant_reward[2]] * abrupt_change_interval
plt.plot([_ for _ in range(len(rews_c))], rews_c, color="red", label="clairvoyant")
plt.axvline(x=100, color="grey", label="abrupt change")
plt.axvline(x=200, color="grey")
plt.legend()
plt.title("Cumulative reward comparison")
plt.show()

regret comparison

In [ ]:
plt.figure(figsize=(8,5))
plt.plot(range(len(mean_regret2)), mean_regret2, color="blue", label="UCBLearnerActive2")
plt.fill_between(range(len(mean_regret2)), (mean_regret2-std_regret2), (mean_regret2+std_regret2), color='b', alpha=.1)

plt.plot(range(len(mean_regret1)), mean_regret1, color="green", label="UCBLearnerActive1")
plt.fill_between(range(len(mean_regret1)), (mean_regret1-std_regret1), (mean_regret1+std_regret1), color='green', alpha=.1)

plt.axvline(x=100, color="grey", label="abrupt change")
plt.axvline(x=200, color="grey")
plt.legend()
plt.title("Regret comparison")
plt.show()

cumulative regret comparison

In [ ]:
plt.figure(figsize=(8,5))
plt.plot(range(len(cum_reg_mean2)), cum_reg_mean2, color="blue", label="UCBLearnerActive2")
plt.fill_between(range(len(cum_reg_mean2)), (cum_reg_mean2-cum_reg_std2), (cum_reg_mean2+cum_reg_std2), color='b', alpha=.1)

plt.plot(range(len(cum_reg_mean1)), cum_reg_mean1, color="green", label="UCBLearnerActive1")
plt.fill_between(range(len(cum_reg_mean1)), (cum_reg_mean1-cum_reg_std1), (cum_reg_mean1+cum_reg_std1), color='green', alpha=.1)

plt.axvline(x=100, color="grey", label="abrupt change")
plt.axvline(x=200, color="grey")
plt.legend()
plt.title("Cumulative regret comparison")
plt.show()


In [ ]:
n_products

In [ ]:
n_arms

In [ ]:
from random import randrange
array = np.zeros((n_products,n_arms))
for i in range(n_products):
    for j in range(n_arms):
        array[i,j] = randrange(1,10) /10

In [ ]:
array

In [ ]:
randrange(0,1)

In [ ]:
cust_json = "customer3_n_s.json"
today_customer = 100
var_cust = 0
p_lambda = 1.0
graph_json = "business_full_graph.json"
abrupt_change_interval = 100

arms = settings.prices
environment = EnvironmentNonStationary(cust_json,today_customer,var_cust,p_lambda, graph_json, arms, abrupt_change_interval)
clairvoyant_arms, clairvoyant_reward, exp_c, s= environment.estimate_clairvoyant()
print("\n", clairvoyant_arms, clairvoyant_reward, exp_c)

## Sliding window

In [ ]:
customers = copy.deepcopy(environment.customers)
for customer in customers:
    customer.set_probability_buy(np.ones_like(customer.get_buy_distribution()))

In [ ]:
rewards_iterations = []
for i in range(NUM_ITERATION):
    ucb6_learner = UCBLearnerSlidingWindow(n_arms, n_products, customers, graph_json, arms, environment.customers_distribution, window_size=50)
    print('Iteration #', i+1)
    for t in range(TIME_HORIZON):
        if t % 10 == 0:
            utils.progress_bar(t, TIME_HORIZON)
        super_arm = ucb6_learner.select_superarm()
        print(super_arm)
        report = environment.round(super_arm)
        ucb6_learner.update(super_arm.copy(), report)
    rewards = ucb6_learner.history_rewards
    rewards_iterations.append(np.array(rewards))
    environment.new_iteration()
rewards_iterations = np.array(rewards_iterations)
rewards_iterations.shape

In [ ]:
ucb6_learner.reports

In [ ]:
plt.figure(figsize=(10, 5))
mean = np.mean(rewards_iterations, axis=0)
stdev = np.std(rewards_iterations, axis=0)

plt.plot(range(len(mean)), mean)
plt.fill_between(range(len(mean)), (mean-stdev), (mean+stdev), color='b', alpha=.1)
rews_c = [clairvoyant_reward[0]] * abrupt_change_interval + [clairvoyant_reward[1]] * abrupt_change_interval + [clairvoyant_reward[2]] * abrupt_change_interval
plt.plot([_ for _ in range(len(rews_c))], rews_c, color="green", label="clairvoyant")
plt.axvline(x=100, color="red", label="first abrupt change")
plt.axvline(x=200, color="orange", label="second abrupt change")
plt.legend()
plt.show()

In [ ]:
plt.figure(figsize=(8,5))
regret = rews_c - rewards_iterations 
mean_regret = np.mean(regret, axis=0)
std_regret = np.std(regret, axis=0)
plt.plot(range(len(mean_regret)), mean_regret)
plt.fill_between(range(len(mean_regret)), (mean_regret-std_regret), (mean_regret+std_regret), color='b', alpha=.1)
plt.axvline(x=100, color="red", label="first abrupt change")
plt.axvline(x=200, color="orange", label="second abrupt change")
plt.legend()
plt.show()

In [ ]:
plt.figure(figsize=(8,5))
regret = rews_c - rewards_iterations 
cumulative_regret = np.cumsum(regret, axis=1)
cum_reg_mean = np.mean(cumulative_regret, axis=0)
cum_reg_std = np.std(cumulative_regret, axis=0)

plt.plot(range(len(cum_reg_mean)), cum_reg_mean)
plt.fill_between(range(len(cum_reg_mean)), (cum_reg_mean-cum_reg_std), (cum_reg_mean+cum_reg_std), color='b', alpha=.1)
plt.axvline(x=100, color="red", label="first abrupt change")
plt.axvline(x=200, color="orange", label="second abrupt change")
plt.legend()
plt.show()

## Comparison between sliding window and Active learner

In [ ]:
plt.figure(figsize=(10, 5))
plt.plot(range(len(mean)), mean, color="blue", label="Sliding window")
plt.fill_between(range(len(mean)), (mean-stdev), (mean+stdev), color='blue', alpha=.1)

plt.plot(range(len(mean1)), mean1, color="green", label="Active learner")
plt.fill_between(range(len(mean1)), (mean1-stdev1), (mean1+stdev1), color='green', alpha=.1)

rews_c = [clairvoyant_reward[0]] * abrupt_change_interval + [clairvoyant_reward[1]] * abrupt_change_interval + [clairvoyant_reward[2]] * abrupt_change_interval
plt.plot([_ for _ in range(len(rews_c))], rews_c)

plt.axvline(x=100, color="grey", label="abrupt change")
plt.axvline(x=200, color="grey")
plt.legend()
plt.title("Reward comparison")
plt.show()

In [ ]:
plt.figure(figsize=(8,5))

plt.plot(range(len(mean_regret)), mean_regret, color="blue", label="Sliding window")
plt.fill_between(range(len(mean_regret)), (mean_regret-std_regret), (mean_regret+std_regret), color='b', alpha=.1)

plt.plot(range(len(mean_regret1)), mean_regret1, color="green", label="Active Learner")
plt.fill_between(range(len(mean_regret1)), (mean_regret1-std_regret1), (mean_regret1+std_regret1), color='b', alpha=.1)

plt.axvline(x=100, color="grey", label="abrupt change")
plt.axvline(x=200, color="grey")
plt.legend()
plt.title("Regret comparison")
plt.show()

In [ ]:
plt.figure(figsize=(8,5))

plt.plot(range(len(cum_reg_mean)), cum_reg_mean, color="blue", label="Sliding window")
plt.fill_between(range(len(cum_reg_mean)), (cum_reg_mean-cum_reg_std), (cum_reg_mean+cum_reg_std), color='b', alpha=.1)

plt.plot(range(len(cum_reg_mean1)), cum_reg_mean1, color="green", label="Active Learner")
plt.fill_between(range(len(cum_reg_mean1)), (cum_reg_mean1-cum_reg_std1), (cum_reg_mean1+cum_reg_std1), color='green', alpha=.1)

plt.show()

In [ ]:
#plt.savefig('foo.pdf')